#!/usr/bin/env python3
"""
UniFi Access Dawn/Dusk Policy Scheduler — Web UI
Made by Frank Gadot (https://github.com/fgadot)
"""

import json
import os
import re
import shlex
import subprocess
from pathlib import Path

import requests
import urllib3
from flask import Flask, jsonify, redirect, render_template, request, url_for

# UniFi controllers use self-signed certs by default — silence urllib3's noise
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ----- Paths (override via env var when testing locally) -----
DATA_DIR = Path(os.environ.get("DATA_DIR", "/data"))
CONFIG_FILE = DATA_DIR / "config.env"
STATUS_FILE = DATA_DIR / "last_run.json"
LOG_FILE = DATA_DIR / "logs" / "run.log"

# Path to the run.sh script. In Docker this is /app/run.sh; locally we look in CWD.
RUN_SCRIPT = os.environ.get("RUN_SCRIPT", "/app/run.sh")

# Fields the setup form collects (and run.sh consumes)
REQUIRED_FIELDS = ["UNIFI_HOST", "UNIFI_TOKEN", "POLICY_NAME", "LAT", "LNG", "TZ"]

app = Flask(__name__)


# ----- Config file helpers --------------------------------------------------

def parse_config_env(path: Path) -> dict:
    if not path.exists():
        return {}
    config = {}
    line_re = re.compile(r'^\s*(?:export\s+)?([A-Z_][A-Z0-9_]*)=(.*)$')
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = line_re.match(line)
        if not m:
            continue
        key, value = m.group(1), m.group(2)
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        config[key] = value
    return config


def write_config_env(path: Path, values: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by the web UI — bash-sourceable"]
    for key in REQUIRED_FIELDS:
        val = values.get(key, "")
        lines.append(f"export {key}={shlex.quote(val)}")
    path.write_text("\n".join(lines) + "\n")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def is_configured(config: dict) -> bool:
    return all(config.get(k) for k in REQUIRED_FIELDS)


# ----- Status / log helpers -------------------------------------------------

def read_status() -> dict | None:
    if not STATUS_FILE.exists():
        return None
    try:
        return json.loads(STATUS_FILE.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def read_log_tail(max_lines: int = 200) -> str:
    if not LOG_FILE.exists():
        return "(no log file yet — run.sh hasn't executed)"
    try:
        lines = LOG_FILE.read_text().splitlines()
        return "\n".join(lines[-max_lines:])
    except OSError as e:
        return f"(could not read log: {e})"


def resolve_run_script() -> Path | None:
    p = Path(RUN_SCRIPT)
    if p.exists():
        return p
    fallback = Path("./run.sh").resolve()
    if fallback.exists():
        return fallback
    return None


# ----- Routes ---------------------------------------------------------------

@app.route("/")
def index():
    config = parse_config_env(CONFIG_FILE)
    edit_mode = request.args.get("edit") == "1"
    if is_configured(config) and not edit_mode:
        return render_template(
            "dashboard.html",
            config=config,
            status=read_status(),
            log=read_log_tail(),
        )
    return render_template("setup.html", config=config)


@app.route("/save", methods=["POST"])
def save():
    values = {k: request.form.get(k, "").strip() for k in REQUIRED_FIELDS}
    missing = [k for k, v in values.items() if not v]
    if missing:
        return render_template(
            "setup.html",
            config=values,
            error=f"Missing required fields: {', '.join(missing)}",
        ), 400
    write_config_env(CONFIG_FILE, values)
    if STATUS_FILE.exists():
        try:
            STATUS_FILE.unlink()
        except OSError:
            pass
    return redirect(url_for("index"))


@app.route("/policies", methods=["POST"])
def policies():
    """
    Test UniFi connection and return the access-policy list.
    Body: {"host": "...", "token": "..."}
    Response: {"ok": bool, "policies": [{"name": "...", "id": "..."}], "error": "..."}
    """
    data = request.get_json(silent=True) or {}
    host = (data.get("host") or "").rstrip("/")
    token = data.get("token") or ""

    if not host or not token:
        return jsonify(ok=False, error="UniFi URL and token are both required."), 400

    url = f"{host}/api/v1/developer/access_policies"
    try:
        resp = requests.get(
            url,
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/json",
            },
            timeout=10,
            verify=False,  # UniFi uses self-signed certs
        )
    except requests.exceptions.ConnectTimeout:
        return jsonify(
            ok=False,
            error="Connection timed out. Check the URL and that the controller is reachable.",
        )
    except requests.exceptions.SSLError as e:
        return jsonify(ok=False, error=f"TLS error: {e}")
    except requests.exceptions.ConnectionError as e:
        return jsonify(
            ok=False,
            error=f"Cannot reach the controller. Check URL, port, and network. ({e.__class__.__name__})",
        )
    except Exception as e:
        return jsonify(ok=False, error=f"Unexpected error: {e}")

    if resp.status_code == 401:
        return jsonify(ok=False, error="Authentication failed (HTTP 401). Token is invalid or expired.")
    if resp.status_code == 403:
        return jsonify(ok=False, error="Forbidden (HTTP 403). The token lacks permission to read access policies.")
    if resp.status_code != 200:
        return jsonify(ok=False, error=f"UniFi returned HTTP {resp.status_code}")

    try:
        body = resp.json()
    except ValueError:
        return jsonify(ok=False, error="Controller returned a non-JSON response.")

    policy_list = body.get("data", []) or []
    simplified = sorted(
        [{"name": p.get("name"), "id": p.get("id")} for p in policy_list if p.get("name")],
        key=lambda p: p["name"].lower(),
    )

    if not simplified:
        return jsonify(
            ok=False,
            error="Connected, but no access policies were found on this controller.",
        )

    return jsonify(ok=True, policies=simplified)


@app.route("/run-now", methods=["POST"])
def run_now():
    script = resolve_run_script()
    if script is None:
        return jsonify(
            ok=False,
            error=f"run.sh not found (looked in {RUN_SCRIPT} and current dir)",
        ), 500

    env = os.environ.copy()
    env.setdefault("LOG_DIR", str(LOG_FILE.parent))
    env.setdefault("STATUS_FILE", str(STATUS_FILE))
    env.setdefault("CONFIG_FILE", str(CONFIG_FILE))
    env.setdefault("DATA_DIR", str(DATA_DIR))

    try:
        proc = subprocess.run(
            ["bash", str(script)],
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
        )
        return jsonify(
            ok=(proc.returncode == 0),
            returncode=proc.returncode,
            stdout=proc.stdout[-4000:],
            stderr=proc.stderr[-4000:],
        )
    except subprocess.TimeoutExpired:
        return jsonify(ok=False, error="run.sh timed out after 120 seconds"), 504
    except Exception as e:
        return jsonify(ok=False, error=str(e)), 500


@app.route("/status.json")
def status_json():
    status = read_status()
    return (json.dumps(status or {}, indent=2), 200,
            {"Content-Type": "application/json"})


@app.route("/logs")
def logs():
    return (read_log_tail(500), 200, {"Content-Type": "text/plain; charset=utf-8"})


@app.route("/healthz")
def healthz():
    return "ok", 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080, debug=True)
